/** Screenshots of the chat's generation states against a running test server (AI_MOCK=1). */
import { chromium, devices } from "@playwright/test";
import { mkdirSync } from "node:fs";
const BASE = process.env.SHOT_BASE ?? "http://localhost:3100";
const OUT = process.env.SHOT_OUT ?? "playwright-report/chat-shots";
mkdirSync(OUT, { recursive: true });
const browser = await chromium.launch();
async function run(ctxOptions, tag) {
  const context = await browser.newContext(ctxOptions);
  const page = await context.newPage();
  const errors = [];
  page.on("console", (m) => (m.type() === "error" || m.type() === "warning") && !m.text().startsWith("Failed to load resource") && errors.push(m.text().slice(0, 200)));
  page.on("pageerror", (e) => errors.push(`pageerror: ${e.message}`));
  page.setDefaultTimeout(60_000);
  const shot = (n) => page.screenshot({ path: `${OUT}/${tag}-${n}.png` });
  await page.goto(`${BASE}/register`);
  await page.getByLabel("Full name").fill("Amol Dev");
  await page.getByLabel("Email").fill(`cs-${Date.now()}-${Math.random().toString(36).slice(2, 6)}@gixxer.test`);
  await page.getByLabel("Password", { exact: true }).fill("Sup3r-secure-pass");
  await page.getByLabel("Confirm password").fill("Sup3r-secure-pass");
  await page.getByRole("button", { name: "Create account" }).click();
  await page.waitForURL(/\/app$/);
  await page.getByRole("button", { name: "Booster off" }).click();
  await page.waitForTimeout(700);
  await shot("booster-glow");
  await page.getByRole("textbox", { name: "Message" }).fill("Explain how a bicycle gear works, with a short code example of a gear ratio function");
  await page.getByRole("button", { name: "Send message" }).click();
  await page.waitForSelector("[data-loader], [data-thinking]");
  await shot("loader");
  await page.waitForSelector("[data-message-status='complete']");
  await page.waitForTimeout(400);
  await shot("reply");
  await page.getByRole("button", { name: "Booster on" }).click();
  await page.getByRole("textbox", { name: "Message" }).fill("Generate an image of a red fox in snow");
  await page.getByRole("button", { name: "Send message" }).click();
  await page.waitForSelector("[data-generating='image']");
  await page.waitForTimeout(500);
  await shot("image-loading");
  await page.waitForSelector("[data-message-role='assistant'] >> nth=1");
  await page.waitForFunction(() => document.querySelectorAll("[data-message-status='complete']").length >= 2);
  await page.waitForTimeout(900);
  await shot("image");
  await page.getByRole("button", { name: /Open image/ }).click();
  await page.waitForTimeout(500);
  await shot("lightbox");
  await page.keyboard.press("Escape");
  await page.getByRole("textbox", { name: "Message" }).fill("Create a PDF about solar panels for homeowners");
  await page.getByRole("button", { name: "Send message" }).click();
  await page.waitForFunction(() => document.querySelectorAll("[data-message-status='complete']").length >= 3);
  await page.waitForTimeout(600);
  await shot("document");
  await page.getByRole("button", { name: /Open file: .*\.pdf/ }).click();
  await page.waitForSelector("[data-page]");
  await page.waitForTimeout(400);
  await shot("document-panel");
  await page.keyboard.press("Escape");
  await page.getByRole("textbox", { name: "Message" }).fill("Make an Excel spreadsheet of five European capitals with their country and population");
  await page.getByRole("button", { name: "Send message" }).click();
  await page.waitForFunction(() => document.querySelectorAll("[data-message-status='complete']").length >= 4);
  await page.waitForTimeout(600);
  await shot("document-xlsx");
  await page.getByRole("button", { name: /Open file: .*\.xlsx/ }).click();
  await page.waitForSelector("[data-sheet-grid]");
  await page.waitForTimeout(400);
  await shot("document-panel-xlsx");
  await page.keyboard.press("Escape");
  await page.goto(`${BASE}/app/plugins`);
  await page.waitForTimeout(500);
  await shot("plugins");
  console.log(`${tag}: errors=${JSON.stringify(errors)}`);
  await context.close();
}
await run({ viewport: { width: 1440, height: 900 } }, "desktop");
await run({ ...devices["Pixel 7"] }, "mobile");
await browser.close();
